services:
  app:
    build:
      context: .      # Контекстом є поточна директорія
    ports:
      - "3000:3000"   # Проброс порту для Flask
    volumes:
      - .:/app        # Прив'язка локальної директорії до контейнера
    depends_on:
      - mongo         # Залежність від MongoDB
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017" # Проброс порту для MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:



